In [37]:
pwd

'/Users/ellismok/Desktop/Challenges/PsciCat-Learners---Final-Project'

In [38]:
# Dependencies and Setup
import pandas as pd
import pathlib
import csv
import scipy.stats as st
import numpy as np
import calendar
from time import strptime
import datetime

In [39]:
# Create paths for csv
CA_unemployment = "./unemployment_dataset/CA_unemployment_rate_data.txt"

In [40]:
# Read csv
CA_unemployment_df = pd.read_csv(CA_unemployment)
pd.DataFrame(CA_unemployment_df)

     Year Period                Area Adjusted Preliminary  Unemployment Rate
0    2021    Jan  Los Angeles County      Adj  Not Prelim               12.6
1    2021    Feb  Los Angeles County      Adj  Not Prelim               11.5
2    2021    Mar  Los Angeles County      Adj  Not Prelim               11.4
3    2021    Apr  Los Angeles County      Adj      Prelim               11.7
4    2020    Jan  Los Angeles County      Adj  Not Prelim                4.8
..    ...    ...                 ...      ...         ...                ...
299  1996    Aug  Los Angeles County      Adj  Not Prelim                7.9
300  1996    Sep  Los Angeles County      Adj  Not Prelim                7.8
301  1996    Oct  Los Angeles County      Adj  Not Prelim                7.8
302  1996    Nov  Los Angeles County      Adj  Not Prelim                7.7
303  1996    Dec  Los Angeles County      Adj  Not Prelim                7.6

[304 rows x 6 columns]

In [41]:
# Combine Year and Period columns to create Date columns
CA_unemployment_df['Date'] = CA_unemployment_df.Year.map(str) + " " + CA_unemployment_df.Period
CA_unemployment_df

,Year,Period,Area,Adjusted,Preliminary,Unemployment Rate,Date
0,2021,Jan,Los Angeles County,Adj,Not Prelim,12.6,2021 Jan
1,2021,Feb,Los Angeles County,Adj,Not Prelim,11.5,2021 Feb
2,2021,Mar,Los Angeles County,Adj,Not Prelim,11.4,2021 Mar
3,2021,Apr,Los Angeles County,Adj,Prelim,11.7,2021 Apr
4,2020,Jan,Los Angeles County,Adj,Not Prelim,4.8,2020 Jan
...,...,...,...,...,...,...,...
299,1996,Aug,Los Angeles County,Adj,Not Prelim,7.9,1996 Aug
300,1996,Sep,Los Angeles County,Adj,Not Prelim,7.8,1996 Sep
301,1996,Oct,Los Angeles County,Adj,Not Prelim,7.8,1996 Oct
302,1996,Nov,Los Angeles County,Adj,Not Prelim,7.7,1996 Nov
303,1996,Dec,Los Angeles County,Adj,Not Prelim,7.6,1996 Dec

In [42]:
# Move the Date up to the front
date_CA_unemployment_df = CA_unemployment_df[ ['Date'] + [ col for col in CA_unemployment_df.columns if col != 'Date' ] ]
date_CA_unemployment_df

,Date,Year,Period,Area,Adjusted,Preliminary,Unemployment Rate
0,2021 Jan,2021,Jan,Los Angeles County,Adj,Not Prelim,12.6
1,2021 Feb,2021,Feb,Los Angeles County,Adj,Not Prelim,11.5
2,2021 Mar,2021,Mar,Los Angeles County,Adj,Not Prelim,11.4
3,2021 Apr,2021,Apr,Los Angeles County,Adj,Prelim,11.7
4,2020 Jan,2020,Jan,Los Angeles County,Adj,Not Prelim,4.8
...,...,...,...,...,...,...,...
299,1996 Aug,1996,Aug,Los Angeles County,Adj,Not Prelim,7.9
300,1996 Sep,1996,Sep,Los Angeles County,Adj,Not Prelim,7.8
301,1996 Oct,1996,Oct,Los Angeles County,Adj,Not Prelim,7.8
302,1996 Nov,1996,Nov,Los Angeles County,Adj,Not Prelim,7.7
303,1996 Dec,1996,Dec,Los Angeles County,Adj,Not Prelim,7.6

In [44]:
# Convert Date column to YYYY-MM-DD
# Option 1: Use the date column and read the format and change to YYYY-MM. THEN add 31st (-31) at the end of all the dates
# Option 2: FIRST reformat all the Period column to MM (e.g. 01, 02, ...). THEN combine Year + Period together. THEN add 31st to all the dates. 

temp = datetime.datetime.strptime('2021 Jan', '%Y %m')
result = temp.strftime('%Y-%m')

ValueError: time data '2021 Jan' does not match format '%Y%m'

In [46]:
# Delete extraneous columns
delete_extraneous_columns = date_CA_unemployment_df.drop(columns= ["Adjusted", "Preliminary"])    
delete_extraneous_columns.head()

       Date  Year Period                Area  Unemployment Rate
0  2021 Jan  2021    Jan  Los Angeles County               12.6
1  2021 Feb  2021    Feb  Los Angeles County               11.5
2  2021 Mar  2021    Mar  Los Angeles County               11.4
3  2021 Apr  2021    Apr  Los Angeles County               11.7
4  2020 Jan  2020    Jan  Los Angeles County                4.8

In [47]:
# Remove the county from each name
delete_extraneous_columns["Area"] = delete_extraneous_columns["Area"].str.replace(" County", "")
delete_extraneous_columns

         Date  Year Period         Area  Unemployment Rate
0    2021 Jan  2021    Jan  Los Angeles               12.6
1    2021 Feb  2021    Feb  Los Angeles               11.5
2    2021 Mar  2021    Mar  Los Angeles               11.4
3    2021 Apr  2021    Apr  Los Angeles               11.7
4    2020 Jan  2020    Jan  Los Angeles                4.8
..        ...   ...    ...          ...                ...
299  1996 Aug  1996    Aug  Los Angeles                7.9
300  1996 Sep  1996    Sep  Los Angeles                7.8
301  1996 Oct  1996    Oct  Los Angeles                7.8
302  1996 Nov  1996    Nov  Los Angeles                7.7
303  1996 Dec  1996    Dec  Los Angeles                7.6

[304 rows x 5 columns]