In [4]:
pwd

'/Users/ellismok/Desktop/Challenges/PsciCat-Learners---Final-Project'

In [5]:
# Dependencies and Setup
import pandas as pd
import pathlib
import csv
import scipy.stats as st
import numpy as np

In [6]:
# Create paths for csv

zip_zhvi_condo_coop = "zillow_dataset/zip_zhvi_condo_coop.csv"

In [8]:
# Read csv

zip_condo_coop_df = pd.read_csv(zip_zhvi_condo_coop)
pd.DataFrame(zip_condo_coop_df)

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,1996-01-31,...,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31,2021-01-31,2021-02-28,2021-03-31,2021-04-30
0,61639,0,10025,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,201172.0,...,1037829.0,1053786.0,1062115.0,1064424.0,1066808.0,1079314.0,1080338.0,1091289.0,1104207.0,1121519.0
1,84654,1,60657,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,230720.0,...,418604.0,420326.0,422557.0,424637.0,426770.0,428721.0,430485.0,432132.0,433153.0,434497.0
2,61637,2,10023,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,225235.0,...,1130964.0,1133286.0,1144356.0,1145196.0,1140547.0,1130929.0,1121601.0,1121172.0,1118435.0,1120741.0
3,91982,3,77494,Zip,TX,TX,Katy,Houston-The Woodlands-Sugar Land,Harris County,NaN,...,203879.0,204686.0,205300.0,206356.0,207699.0,210326.0,213242.0,216934.0,221075.0,225963.0
4,84616,4,60614,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,264697.0,...,484985.0,486879.0,489374.0,491563.0,493951.0,496391.0,498745.0,501275.0,503147.0,505244.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10919,93733,34322,81225,Zip,CO,CO,Mount Crested Butte,NaN,Gunnison County,105181.0,...,289822.0,291217.0,293776.0,296362.0,299804.0,302646.0,304805.0,306677.0,308380.0,311595.0
10920,75924,34322,41101,Zip,KY,KY,Ashland,Huntington-Ashland,Boyd County,106068.0,...,91533.0,91571.0,92541.0,93352.0,94498.0,95804.0,97668.0,98192.0,98421.0,98872.0
10921,59147,34430,3575,Zip,TX,TX,Clifton,NaN,Bosque County,NaN,...,494353.0,495500.0,492947.0,494381.0,501256.0,508855.0,513748.0,512703.0,513530.0,516380.0
10922,61694,34430,10118,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,1769224.0,...,2452911.0,2429431.0,2394813.0,2374899.0,2345430.0,2319936.0,2292620.0,2273340.0,2276950.0,2275754.0
10923,95851,34430,89155,Zip,NV,NV,Las Vegas,Las Vegas-Henderson-Paradise,Clark County,72689.0,...,132550.0,133812.0,135676.0,137098.0,138336.0,139131.0,140158.0,141522.0,143752.0,145349.0

In [11]:
# Create a smaller df to test on 
testing_condo_df = zip_condo_coop_df.head(50)
testing_condo_df.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,1996-01-31,...,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31,2021-01-31,2021-02-28,2021-03-31,2021-04-30
0,61639,0,10025,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,201172.0,...,1037829.0,1053786.0,1062115.0,1064424.0,1066808.0,1079314.0,1080338.0,1091289.0,1104207.0,1121519.0
1,84654,1,60657,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,230720.0,...,418604.0,420326.0,422557.0,424637.0,426770.0,428721.0,430485.0,432132.0,433153.0,434497.0
2,61637,2,10023,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,225235.0,...,1130964.0,1133286.0,1144356.0,1145196.0,1140547.0,1130929.0,1121601.0,1121172.0,1118435.0,1120741.0
3,91982,3,77494,Zip,TX,TX,Katy,Houston-The Woodlands-Sugar Land,Harris County,NaN,...,203879.0,204686.0,205300.0,206356.0,207699.0,210326.0,213242.0,216934.0,221075.0,225963.0
4,84616,4,60614,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,264697.0,...,484985.0,486879.0,489374.0,491563.0,493951.0,496391.0,498745.0,501275.0,503147.0,505244.0

In [ ]:
# Name is id_vars and Course is value_vars
testing_condo_df.melt(df, id_vars =['Name'], value_vars =['Course'])